# Generated by Django 5.2.12 on 2026-05-29 06:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Latest Version')),
                ('minimum_version', models.CharField(max_length=20, verbose_name='Minimum Supported Version')),
                ('download_url', models.URLField(verbose_name='Download URL (.zip)')),
                ('release_url', models.URLField(blank=True, verbose_name='Release Page URL')),
                ('message', models.TextField(blank=True, verbose_name='Update Message')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Release',
                'verbose_name_plural': 'App Releases',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='License Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note (tên/SĐT khách)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hwid_reset_count', models.IntegerField(default=0, verbose_name='HWID Reset Count')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Device Token')),
                ('hwid', models.CharField(max_length=64, verbose_name='HWID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Seen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='licenses.license')),
            ],
            options={
                'verbose_name': 'Device Session',
                'verbose_name_plural': 'Device Sessions',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(blank=True, max_length=36)),
                ('hwid', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('result', models.CharField(choices=[('ok', 'OK'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('device_mismatch', 'Device Mismatch'), ('not_found', 'Not Found'), ('invalid_request', 'Invalid Request'), ('rate_limited', 'Rate Limited')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='licenses.license')),
            ],
            options={
                'verbose_name': 'Validate Log',
                'verbose_name_plural': 'Validate Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
