# Generated by Django 5.2.12 on 2026-05-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppRelease',
        ),
    ]
