# Generated by Django 5.2.12 on 2026-05-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='thumbnail_url',
            field=models.ImageField(blank=True, upload_to='resource_thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
